### ISSUE TITLE
New image

### ISSUE THREAD

**Issue by aphextwinfan82** [Tobsta/ImageEditor#1]
![screenshot 2018-06-12 at 6 26 28 pm](https://user-images.githubusercontent.com/40197847/41278819-2f76bf7e-6e6e-11e8-806a-934194f82cea.png)
Doesn't let you work on a new image

**Comment by OliverBalfour** [comment]
Just added new image functionality, thanks for pointing that out. For the moment it just overwrites the existing image, though I'm planning on adding support for editing multiple images concurrently soon.
